In [5]:
import numpy
import pandas as pd

In [6]:
raw_data = pd.read_csv('/content/diabetes.csv')

In [7]:
raw_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [8]:
# Shape of the dataset
raw_data.shape

(768, 9)

In [9]:
# Column names
raw_data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
# Column types
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [11]:
# Null values
raw_data.isnull().sum()

,0
Pregnancies,0
Glucose,0
BloodPressure,0
SkinThickness,0
Insulin,0
BMI,0
DiabetesPedigreeFunction,0
Age,0
Outcome,0


In [12]:

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [13]:
# Splitting into dependant and independant features
x = raw_data.drop(['Outcome'],axis=1)
y = raw_data['Outcome']

In [14]:
#  Train-Test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [15]:
x_train.shape[1]

8

In [16]:
from sklearn.preprocessing import StandardScaler

# feature scaling
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [17]:
#building the NN using Tensorflow and Keras - we build it like a Sequential Model with layers stacked on top of each other
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), #input_layer has 8 neurons
    layers.Dense(10,activation='relu',name='hidden_layer_1'), #hidden_layer_1 has 10 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 16 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [18]:
# Compiling the model
model.compile(
    optimizer='adam', #optimizer will ensure that the gradient loss is within the range
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [19]:
results = model.fit(x_train_scaled,y_train,epochs=10,batch_size=16,validation_split=0.2,
    verbose=1)


Epoch 1/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6652 - loss: 0.6601 - val_accuracy: 0.6724 - val_loss: 0.6558
Epoch 2/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7196 - loss: 0.6323 - val_accuracy: 0.7155 - val_loss: 0.6311
Epoch 3/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7130 - loss: 0.6053 - val_accuracy: 0.7241 - val_loss: 0.6071
Epoch 4/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7174 - loss: 0.5800 - val_accuracy: 0.7241 - val_loss: 0.5839
Epoch 5/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7196 - loss: 0.5576 - val_accuracy: 0.7500 - val_loss: 0.5632
Epoch 6/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7261 - loss: 0.5387 - val_accuracy: 0.7500 - val_loss: 0.5459
Epoch 7/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7370 - loss: 0.5253 - val_accuracy: 0.7500 - val_loss: 0.5293
Epoch 8/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7304 - loss: 0.5134 - val_accuracy: 0.7586 - val_loss

In [21]:
# 8->10->16->1
history_df = pd.DataFrame({
    "Epoch": range(1, len(results.history["accuracy"]) + 1),
    "Train Accuracy": results.history["accuracy"],
    "Validation Accuracy": results.history["val_accuracy"],
    "Train Loss": results.history["loss"],
    "Validation Loss": results.history["val_loss"]
})

history_df

,Epoch,Train Accuracy,Validation Accuracy,Train Loss,Validation Loss
0,1,0.665217,0.672414,0.660053,0.655787
1,2,0.719565,0.715517,0.632308,0.631099
2,3,0.713043,0.724138,0.605302,0.607132
3,4,0.717391,0.724138,0.580014,0.583862
4,5,0.719565,0.750000,0.557554,0.563195
5,6,0.726087,0.750000,0.538738,0.545903
6,7,0.736957,0.750000,0.525339,0.529292
7,8,0.730435,0.758621,0.513422,0.518460
8,9,0.736957,0.767241,0.505223,0.509345
9,10,0.741304,0.767241,0.498519,0.501949


In [22]:
y_pred=model.predict(x_test_scaled)
print(y_pred[:10])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[[0.18378182]
 [0.7185974 ]
 [0.21287856]
 [0.07206048]
 [0.159534  ]
 [0.387535  ]
 [0.10981151]
 [0.47262067]
 [0.6494642 ]
 [0.47745118]]


In [23]:
#  generate predictions on test dataset
predictions = (y_pred > 0.5).astype(int)
print(predictions[:10])

[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]


In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, predictions)

print("Test Accuracy:", accuracy)

print(confusion_matrix(y_test, predictions))

print(classification_report(y_test, predictions))

Test Accuracy: 0.78125
[[116   8]
 [ 34  34]]
              precision    recall  f1-score   support

           0       0.77      0.94      0.85       124
           1       0.81      0.50      0.62        68

    accuracy                           0.78       192
   macro avg       0.79      0.72      0.73       192
weighted avg       0.79      0.78      0.77       192

